- hosts: all
  become: yes
  tasks:
   - name: install Docker
     apt:
       name: docker.io
       state: present
       update_cache: true

   - name: Copy daemon.json in VM
     ansible.builtin.template:
       src: /Users/federico/desktop/fomazione_cm/daemon.json
       dest: /etc/docker/
       owner: root
       group: root
       mode: "0740"

   - name: Restart docker daemon after copy daemon.json
     service:
        name: docker
        state: restarted

- hosts: node1
  become: yes
  tasks:
   - name: Create Docker Registry
     docker_container:
       name: registry
       image: registry
       state: started
       ports:
         - "5000:5000"